import os
import numpy as np
import pandas as pd
import pickle
import re

def read_joules(f,device):
    ''' Reads a joules trace csv generated by run_experiment.py'''
    joules_df = pd.read_csv(f)
    jcols = joules_df.columns

    regex = re.compile('package_.')
    package_cols = [string for string in jcols if re.match(regex, string)]

    regex = re.compile('dram_.')
    dram_cols = [string for string in jcols if re.match(regex, string)]
    
    joules_df['package_total'] = joules_df[package_cols].sum(axis=1)
    joules_df['dram_total'] = joules_df[dram_cols].sum(axis=1)

    if device == 'cuda':
        joules_df['nvidia_total'] = joules_df['nvidia_gpu_0']
    else:
        joules_df['nvidia_total'] = 0

    joules_df['process_total'] = joules_df['package_total'] + joules_df['dram_total'] + joules_df['nvidia_total']
    joules_df['device'] = device

    return joules_df


def convert_str_to_param_value(df, param_col):
    param_df = pd.DataFrame()
    param_df[[param_col,'unit']] = df[param_col].str.split(' ',expand=True)
    param_df.loc[param_df['unit'].isin(['k','kMac']),param_col] = param_df[param_df['unit'].isin(['k','kMac'])][param_col].astype(float).values*1e3
    param_df.loc[param_df['unit'].isin(['M','MMac']),param_col] = param_df[param_df['unit'].isin(['M','MMac'])][param_col].astype(float).values*1e6
    param_df.loc[param_df['unit'].isin(['G','GMac']),param_col] = param_df[param_df['unit'].isin(['G','GMac'])][param_col].astype(float).values*1e9
    df[param_col] = param_df[param_col]
    return df